config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get 'static_pages/home'
  get 'static_pages/about'
  get 'static_pages/contact'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | A to Z Coaching</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta charset="utf-8">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <div class="main">

      <div class="nav">
        <ul>
          <li><%= link_to 'Home', root_path %></li>
          <li><%= link_to 'About', static_pages_about_path %></li>
          <li><%= link_to 'Contact', static_pages_contact_path %></li>
        </ul>
      </div>
      
      <%= yield %>

      <footer>
        <p>A to Z Coaching &#xA9; 2023</p>
      </footer>
    </div>
  </body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>

<div class="hero about">
  <div class="title">
    <h1>A to Z Coaching</h1>
  </div>
</div>

<div class="content">
  <div class="text">
    <h2>About A to Z Coaching</h2>
    <p> 

My clinical experience includes facilitating support groups in a variety of settings,  including Mental Health Systems (MHS) in the CalWORKs Multiservice Center, Tri-City Medical Center Behavioral Health Unit, and Cooperation Over Conflict (CORC) Counseling Services, covering a broad range of topics including Healthy Habits, Victims of Domestic Violence, Family Dynamics, Anger Management, Managing Mood, Life-Skills, and Positive Communication. In addition to facilitating support groups, I have provided, and continue to provide therapeutic counseling to adolescents, teens, individuals, family units and couples. My approach is compassionate, strength-based, person-centered, and holistic I am a member of California Marriage and Family Therapist (CAMFT) and a full member of EMDRIA as a certified EMDR therapist.
    </p>
    <p> 
My education encompasses attending UCLA earning my BA in psychology; attending CSUSM for my multiple subject teaching credential; and attending National University earning my MA in Counseling Psychology. I’m proud to be a California native with four wonderful children, three amazing grand-children, and a determined elderly parent in her 90’s. I’m passionate about being a therapist and count it an honor to work along-side my clients, in a confidential, inviting, nurturing, safe and warm space.
    </p>
  </div>
  <div class="image">
    <%= image_tag 'Mary_Roberts.jpg', alt: 'photo of Mary Roberts', style: 'display: flex; width: 150px;' %>
  </div>
</div>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>

<div class="hero contact">
  <div class="title">
    <h1>A to Z Coaching</h1>
  </div>
</div>

<div class="main-content">
  <div class="title">
    <h2>Contact A to Z Coaching</h2>
  </div>
  <div class="contact-information">
    <p>You can reach A to Z Coaching by emailing <strong>maryinsanclemente@gmail.com</strong>.</p>
  </div>

</div>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>

<div class="hero home">
  <div class="title">
    <h1>A to Z Coaching</h1>
  </div>
</div>

<div class="approach">
  <div class="info">
    <h2>Coaching Approach</h2>
    <p>
Life is an incredible journey filled with challenges, exciting milestones, and unexpected twists and turns. Sometimes having a trained professional to talk with and share life’s challenges is beneficial to explore feelings, learn new skills, and tap into strengths and strategies.
    </p>
    <p>
As a Licensed Marriage and Family Therapist and a California credentialed teacher, I have over 18 years of experience working with families, teens, children, couples, and individuals. My work centers around people and my goal is to help people discover and learn to integrate and work with their strengths, passion, and potential. I integrate my therapeutic education and experience to empower, to encourage, and to equip the people I work with in a mindful “here and now” way.
    </p>
    </div>
</div>

<div class="about-coach">
  <div class="image">
    <%= image_tag 'Mary_Roberts.jpg', alt: 'photo of Mary Roberts', style: 'display: flex; width: 150px;' %>
  </div>
  <div class="text">
    <p>Mary Roberts is an experienced LMFT therapist with an BA in Psychology from UCLA and an MA in Counseling Psychology from National University.</p>
    <p>Her coaching centers on developing effective life skills, healthy habits, positive communication, and improving family dynamics.
  </div>
</div>